[package]
name = "my_rust_project"
version = "0.1.0"
edition = "2021"


[dependencies]
pyo3 = { version = "0.20.2", features = ["extension-module"] }

[lib]
name = "my_rust_project"
crate-type = ["cdylib"]