[package]
name = "my_rust_project"
version = "0.1.0"
edition = "2021"


[dependencies]
my_rust_project1 = { path = "../my_rust_project1" }
pyo3 = { version = "0.20.2", features = ["extension-module"] }

[lib]
name = "my_rust_project"
crate-type = ["cdylib"]